/* Central catalogue data for The Perfume Shop.
   Keeping product names, prices and images in one file prevents the catalogue,
   product-detail page and cart from drifting out of sync. */
window.PERFUME_PRODUCTS = [
  {
    id: '1',
    name: 'Art of Universe',
    category: 'fragrances',
    categoryLabel: 'Fragrances',
    price: 85000,
    image: 'images/art-of-universe-perfume.jpg',
    alt: 'Art of Universe perfume bottle displayed against a soft background',
    description: 'A luxurious fragrance with celestial notes of vanilla, warm woods and sandalwood.',
    notes: 'Vanilla · Sandalwood · Warm woods',
    stock: true,
    featured: true
  },
  {
    id: '2',
    name: 'Atlantis',
    category: 'fragrances',
    categoryLabel: 'Fragrances',
    price: 75000,
    image: 'images/atlantis-perfume.jpg',
    alt: 'Atlantis perfume bottle from The Perfume Shop catalogue',
    description: 'A fresh aquatic fragrance with oceanic, citrus and aromatic notes.',
    notes: 'Citrus · Marine accord · Aromatic herbs',
    stock: true,
    featured: true
  },
  {
    id: '3',
    name: 'Club de Nuit',
    category: 'fragrances',
    categoryLabel: 'Fragrances',
    price: 95000,
    image: 'images/club-de-nuit-perfume.jpg',
    alt: 'Club de Nuit perfume bottle with dark luxury packaging',
    description: 'A sophisticated blend of spices, citrus and woody notes for a polished evening scent.',
    notes: 'Citrus · Spice · Woods',
    stock: true,
    featured: true
  },
  {
    id: '4',
    name: 'Art of Arabia III',
    category: 'fragrances',
    categoryLabel: 'Fragrances',
    price: 120000,
    image: 'images/art-of-arabia-iii-perfume.jpg',
    alt: 'Art of Arabia III perfume bottle in warm neutral tones',
    description: 'An opulent oriental fragrance built around oud, amber and rose accords.',
    notes: 'Oud · Amber · Rose',
    stock: true,
    featured: false
  },
  {
    id: '5',
    name: 'Khamrah Lattafa',
    category: 'fragrances',
    categoryLabel: 'Fragrances',
    price: 68000,
    image: 'images/khamrah-lattafa-perfume.jpg',
    alt: 'Khamrah Lattafa perfume bottle with decorative glass design',
    description: 'A rich aromatic fragrance with warm spices, sweet facets and smooth musky undertones.',
    notes: 'Warm spice · Sweet notes · Musk',
    stock: true,
    featured: false
  },
  {
    id: '6',
    name: 'Proud of You Amber',
    category: 'fragrances',
    categoryLabel: 'Fragrances',
    price: 62000,
    image: 'images/proud-of-you-amber-perfume.webp',
    alt: 'Proud of You Amber fragrance bottle',
    description: 'A warm and sensual amber fragrance with hints of vanilla and sandalwood.',
    notes: 'Amber · Vanilla · Sandalwood',
    stock: true,
    featured: false
  },
  {
    id: '7',
    name: 'Scentemy',
    category: 'fragrances',
    categoryLabel: 'Fragrances',
    price: 55000,
    image: 'images/scentemy-perfume.jpg',
    alt: 'Scentemy perfume bottle shown in The Perfume Shop catalogue',
    description: 'A bright, easy-wearing fragrance with fresh fruity notes for everyday use.',
    notes: 'Fresh fruit · Soft musk · Clean woods',
    stock: true,
    featured: false
  },
  {
    id: '8',
    name: 'Asad',
    category: 'fragrances',
    categoryLabel: 'Fragrances',
    price: 70000,
    image: 'images/asad-perfume.jpg',
    alt: 'Asad perfume bottle with black and gold detailing',
    description: 'A bold warm fragrance with spicy, smoky and woody notes balanced by sweetness.',
    notes: 'Spice · Smoke · Woods',
    stock: true,
    featured: true
  },
  {
    id: '9',
    name: 'Amber Room Diffuser',
    category: 'home-fragrances',
    categoryLabel: 'Home Fragrances',
    price: 42000,
    image: 'images/amber-room-home-fragrance.jpg',
    alt: 'Amber-toned home fragrance collection used for the Amber Room Diffuser',
    description: 'A warm home scent designed to bring amber, resin and soft vanilla notes into a room.',
    notes: 'Amber · Resin · Vanilla',
    stock: true,
    featured: false
  },
  {
    id: '10',
    name: 'Vanilla Oud Home Fragrance',
    category: 'home-fragrances',
    categoryLabel: 'Home Fragrances',
    price: 39000,
    image: 'images/vanilla-oud-home-fragrance.jpg',
    alt: 'Perfume collection image used for Vanilla Oud home fragrance',
    description: 'A comforting home fragrance combining creamy vanilla with a smooth oud-inspired base.',
    notes: 'Vanilla · Oud accord · Soft woods',
    stock: true,
    featured: false
  }
];
